### PR TITLE
Feature/conan

### LINKED ISSUE #10: Build Conan on CI
What?  
Provide support on Travis and Appveyor to build Conan package

Why?  
For now it's only possible to validate Conan package by standalone build

How?  
- Use Conan package tools to execute all jobs
- Collect the package reference by cmake.
- Only upload Conan package when create project tag

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

This PR brings some improvements using Conan:

- Moved test_package to .conan
- Support to build on Windows
- Added build.py to run over CI
- Added Job on Travis CI
- Added job on Appveyor
- Removed rule to run CI only when master

/cc @pleroux0

Close #10

### CODE REVIEW

**Comment by uilianries** [comment]
@d-frey I'm curious why PEGTL and operators use different targets on CMake.

PEGTL installs it cmake config file at share/pegtl/cmake/pegtl-config.cmake,  
and it target is taocpp::PEGTL

However, operators uses a different way:  
operatos installs it cmake config file at share/tao/operators/cmake/taocpp-operators-config.cmake  
and it target is taocpp::taocpp-operators

Should operators follow the same style from PEGTL?

**Comment by d-frey** [comment]
Yes, the taocpp-operators is the remnant of when I thought that the package name alone might conflict with others when not unique enough. Most importantly for the JSON library. "json" itself would cause conflict or confusion, but I guess it should always be used in context in CMake an Conan.

I think we would (for json) end up with taocpp::json and json/<VERSION>@taocpp/stable, both of which are fine. So, please change taocpp::taocpp-operators to taocpp::operators. Within CMake that will still be an alias to taocpp-operators? If this could be removed it would also be fine with me.

**Comment by d-frey** [comment]
About the path I'm actually not sure. Long term the goal was that you could install multiple libraries from taocpp into one tree. Given some top-level directory `<PATH>`, and after installing the libraries somehow, the resulting files would be

```
<PATH>/include/tao/operators.hpp
<PATH>/include/tao/pegtl.hpp
<PATH>/include/tao/pegtl/*
<PATH>/include/tao/json.hpp
<PATH>/include/tao/json/*
<PATH>/include/tao/postgres.hpp
<PATH>/include/tao/postgres/*
<PATH>/lib/libtaopostgres.a
<PATH>/lib/libtaopostgres.so
```

Of course there should also be a place for the `LICENSE` files, maybe `<PATH>/share/tao/pegtl/LICENSE` and we could also add a small `README` next to it pointing users to GitHub or our support email, etc. for documentation, help, etc.

This would allow projects using multiple of taocpp's libraries to only add one path to the command line, `-I <PATH>/include` for compiling and  `-L <PATH>/lib -l libtaopostgres` for linking. This would be nice for people that have their own build system, e.g. us in the company where we have a `Makefile` and the command line for the compiler is quite clean.

The paths you are currently seeing are partially from @pleroux for the Conan files. I haven't looked into that part so far, but I probably should have. Given the typical use-cases (install system wide, install for my user, install locally for my project (locally in a path I give it manually)), how would a Conan package be installed and where would the files end up? Where will the generated files for `CMake` to then find and use the package/library be placed? If you could point me to some documentation from Conan explaining that part, that would be helpful. :)

**Comment by pleroux0** [comment]
Hi

CMake 3.2 searches in the following directories

```
<prefix>/                                               (W)
<prefix>/(cmake|CMake)/                                 (W)
<prefix>/<name>*/                                       (W)
<prefix>/<name>*/(cmake|CMake)/                         (W)
<prefix>/(lib/<arch>|lib|share)/cmake/<name>*/          (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/                (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/  (U)
```

for each prefix provided by CMake. (W)indows and (U)nix is where the search convention comes from, but all paths are searched regardless. Additional paths are search for MaxOS, but those are never searched on Windows or Linux. See [documentation](https://cmake.org/cmake/help/v3.11/command/find_package.html).

Currently with `share/tao/operators/cmake/taocpp-operators-config.cmake` CMake does not find operators, because of the additional tao directory. To avoid naming conflicts I think `share/taocpp-operators/taocpp-operators-config.cmake` will be fine and you only need to point to the installation prefix to find all cmake configs installed there. For example: If I install to `~/.local` then I can just point cmake to `~/.local` there and it finds all packages installed there. The `include` and `lib` structure should stay as is.

When using conan the package is installed in the local conan cache and using `cmake_paths` generator conan creates a toolchain file that CMake can use which sets the `CMAKE_PREFIX_PATH` which allows cmake to find the conan packages when using `find_package(<name>)`. This allows the `CMakeLists.txt` to transparently use conan. Using other generators is also possible. I just really like the `cmake_paths` generator since I don't need any conan commands in my `CMakeLists.txt` (provided that all the dependencies support CMake).

The conan cache has it's own structure which allows it to have multiple versions of the same package as well as multiple builds of the same version when there is ABI differences (compiled with libstdc++11 vs libc++ for example). conan handles all this for you and you don't ever need to specify the path yourself.

I used the `share/<name>/cmake`convention for PEGTL since the folder was already used for the license folder so it made sense to put it there. 

I think the cmake config should be named `taocpp-operators` to prevent naming conflicts. Which can then be found with `find_package(taocpp-operators)`. Since cmake targets can have namespaces, just using taocpp namespace will be sufficient (taocpp::operators when linking to target) and taocpp is also in the conan package name so the extra taocpp is a bit cumbersome.

If you have any more questions about using conan with cmake just ask me on slack. I'd be happy to explain.

**Comment by uilianries** [comment]
UPDATE:

I just renamed the target to `taocpp::operators`

The cmake install dir was replaced by `taocpp-operators`, as @pleroux0 suggedted

Also, I used https://github.com/taocpp/PEGTL/pull/118 as reference to update the tests

To check if cmake is working, I added a job on Travis. It will build and test the project

**Pull request merged**
